"""empty message

Revision ID: 694bdb1d5913
Revises: 
Create Date: 2019-06-26 17:44:17.577680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694bdb1d5913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('issue', sa.String(length=32), nullable=True),
    sa.Column('brief', sa.String(length=128), nullable=True),
    sa.Column('solution', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    # ### end Alembic commands ###
